### ISSUE TITLE
No module named google.protobuf

### ISSUE THREAD

**Issue by anitagraser** [magdawegrzyn/TSP_plugin#3]
Hi, I'm trying to test the plugin. I pip installed google (protobuf is also installed) but still get

> The plugin is broken. Python said: No module named google.protobuf

System: QGIS 2.18.21 on Win10

**Comment by anitagraser** [comment]
Oh, the site-packages folder is empty in the published version

**Comment by magdawegrzyn** [comment]
Should be fixed in version 0.4.

**Comment by anitagraser** [comment]
Confirmed
